# Generated by Django 2.1.3 on 2018-11-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SI_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('backup', models.CharField(blank=True, max_length=50)),
                ('sessionTime_from', models.CharField(default='', max_length=50)),
                ('sessionTime_to', models.CharField(default='', max_length=50)),
                ('room', models.CharField(default='', max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('crn', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['sessionTime_from'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('hours', models.IntegerField(default=0)),
                ('subject1', models.CharField(default='', max_length=50)),
                ('subject2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='si_session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CS416Project.Tutor'),
        ),
    ]
