# Generated by Django 2.1.3 on 2018-12-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0001_initial'),
    ]

    operations = [
      
        migrations.AlterModelOptions(
            name='si_session',
            options={'ordering': ['day', 'sessionTime_from']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['firstname']},
        ),
        migrations.AddField(
            model_name='tutor',
            name='typeofstaff',
            field=models.CharField(choices=[('', '--------'), ('EA', 'EA'), ('SA', 'SA'), ('Work Study', 'Work Study'), ('Volunteer', 'Volunteer')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tutor',
            name='usedhours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='crn',
            field=models.CharField(choices=[('', '--------'), ('2133', '2134'), ('2435', '2435'), ('1341', '1341')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='day',
            field=models.CharField(choices=[('', '--------'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sarturday', 'Satruday'), ('Sunday', 'Sunday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='professor',
            field=models.CharField(choices=[('', '--------'), ('Smith', 'Smith'), ('Thomas', 'Thomas'), ('Daddona', 'Daddona')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='room',
            field=models.CharField(choices=[('', '--------'), ('blue', 'blue'), ('yellow', 'yellow'), ('pink', 'pink')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='sessionTime_from',
            field=models.CharField(choices=[('', '--------'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '1:00'), ('13:30', '1:30'), ('14:00', '2:00'), ('14:30', '2:30'), ('15:00', '3:00'), ('15:30', '3:30'), ('16:00', '4:00'), ('16:30', '4:30'), ('17:00', '5:00'), ('17:30', '5:30'), ('18:00', '6:00'), ('18:30', '6:30'), ('19:00', '7:00'), ('19:30', '7:30'), ('20:00', '8:00'), ('20:30', '8:30')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='sessionTime_to',
            field=models.CharField(choices=[('', '--------'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '1:00'), ('13:30', '1:30'), ('14:00', '2:00'), ('14:30', '2:30'), ('15:00', '3:00'), ('15:30', '3:30'), ('16:00', '4:00'), ('16:30', '4:30'), ('17:00', '5:00'), ('17:30', '5:30'), ('18:00', '6:00'), ('18:30', '6:30'), ('19:00', '7:00'), ('19:30', '7:30'), ('20:00', '8:00'), ('20:30', '8:30')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject1',
            field=models.CharField(choices=[('', '--------'), ('Math', 'Math'), ('English', 'English'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer', 'Computer')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject2',
            field=models.CharField(blank=True, choices=[('', '--------'), ('Math', 'Math'), ('English', 'English'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer', 'Computer')], default='', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tutor',
            unique_together={('firstname', 'lastname')},
        ),
        migrations.AddField(
            model_name='timetable',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Tutor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Tutor'),
        ),
    ]
