# Generated by Django 2.1.3 on 2018-12-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0001_initial'),
    ]

  
    ]
