# Generated by Django 2.1.3 on 2018-11-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0002_auto_20181121_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['-id']},
        ),
    ]
