# Generated by Django 2.1.3 on 2018-11-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0003_auto_20181121_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['-firstname']},
        ),
    ]
