# Generated by Django 2.1.3 on 2018-11-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0004_auto_20181121_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='si_session',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['firstname']},
        ),
        migrations.AlterField(
            model_name='si_session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Tutor'),
        ),
    ]
