# Generated by Django 2.1.3 on 2018-11-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0005_auto_20181121_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='si_session',
            options={'ordering': ['day', 'sessionTime_from']},
        ),
    ]
