# Generated by Django 2.1.3 on 2018-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0006_auto_20181121_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_session',
            name='day',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=50),
        ),
    ]
