# Generated by Django 2.1.3 on 2018-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0007_auto_20181121_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_session',
            name='day',
            field=models.CharField(choices=[('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=50),
        ),
    ]
