# Generated by Django 2.1.3 on 2018-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0009_auto_20181121_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_session',
            name='room',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='', max_length=50),
        ),
    ]
