# Generated by Django 2.1.3 on 2018-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0011_auto_20181121_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_session',
            name='room',
            field=models.CharField(choices=[('', '--------'), ('blue', 'blue'), ('yellow', 'yellow'), ('pink', 'pink')], default='', max_length=50),
        ),
    ]
