# Generated by Django 2.1.3 on 2018-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0013_auto_20181121_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_session',
            name='day',
            field=models.CharField(choices=[('', '--------'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sarturday', 'Satruday'), ('Sunday', 'Sunday')], max_length=50),
        ),
    ]
