# Generated by Django 2.1.3 on 2018-11-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0016_auto_20181121_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_session',
            name='crn',
            field=models.CharField(choices=[('', '--------'), ('2133', '2134'), ('2435', '2435'), ('1341', '1341')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='professor',
            field=models.CharField(choices=[('', '--------'), ('Smith', 'Smith'), ('Thomas', 'Thomas'), ('Daddona', 'Daddona')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='sessionTime_from',
            field=models.CharField(choices=[('', '--------'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='si_session',
            name='sessionTime_to',
            field=models.CharField(choices=[('', '--------'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30')], default='', max_length=50),
        ),
    ]
