# Generated by Django 2.1.3 on 2018-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0020_auto_20181122_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
