# Generated by Django 2.1.3 on 2018-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0021_tutor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject1',
            field=models.CharField(choices=[('', '--------'), ('Math', 'Math'), ('English', 'English'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer', 'Computer')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject2',
            field=models.CharField(choices=[('', '--------'), ('Math', 'Math'), ('English', 'English'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer', 'Computer')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='type',
            field=models.CharField(choices=[('', '--------'), ('EA', 'EA'), ('SA', 'SA'), ('Work Study', 'Work Study'), ('Volunteer', 'Volunteer')], default='', max_length=50),
        ),
    ]
