# Generated by Django 2.1.3 on 2018-11-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0022_auto_20181122_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='type',
            new_name='typeofstaff',
        ),
    ]
