# Generated by Django 2.1.3 on 2018-11-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0023_auto_20181124_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t0900', models.BooleanField(null=True)),
                ('t0930', models.BooleanField(null=True)),
                ('t1000', models.BooleanField(null=True)),
                ('t1030', models.BooleanField(null=True)),
                ('t1100', models.BooleanField(null=True)),
                ('t1130', models.BooleanField(null=True)),
                ('t1200', models.BooleanField(null=True)),
                ('t1300', models.BooleanField(null=True)),
                ('t1330', models.BooleanField(null=True)),
                ('t1400', models.BooleanField(null=True)),
                ('t1430', models.BooleanField(null=True)),
                ('t1500', models.BooleanField(null=True)),
                ('t1530', models.BooleanField(null=True)),
                ('t1600', models.BooleanField(null=True)),
                ('t1630', models.BooleanField(null=True)),
                ('t1700', models.BooleanField(null=True)),
                ('t1730', models.BooleanField(null=True)),
                ('t1800', models.BooleanField(null=True)),
                ('t1830', models.BooleanField(null=True)),
                ('t1900', models.BooleanField(null=True)),
                ('t1930', models.BooleanField(null=True)),
                ('t2000', models.BooleanField(null=True)),
                ('t2030', models.BooleanField(null=True)),
                ('t2100', models.BooleanField(null=True)),
            ],
        ),
    ]
