# Generated by Django 2.1.3 on 2018-11-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0025_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='t0900',
        ),
    ]
