# Generated by Django 2.1.3 on 2018-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0027_auto_20181125_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='shedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='From1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='From2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='To1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='To2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('', '--------'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sarturday', 'Satruday'), ('Sunday', 'Sunday')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
