# Generated by Django 2.1.3 on 2018-11-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0029_auto_20181125_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
