# Generated by Django 2.1.3 on 2018-11-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0031_auto_20181125_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day', 'tutor__firstname']},
        ),
        migrations.AlterUniqueTogether(
            name='tutor',
            unique_together={('firstname', 'lastname')},
        ),
    ]
