# Generated by Django 2.1.3 on 2018-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0032_auto_20181126_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='usedhours',
            field=models.IntegerField(default=0),
        ),
    ]
