# Generated by Django 2.1.3 on 2018-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0033_schedule_usedhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='usedhours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='usedhours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
