# Generated by Django 2.1.3 on 2018-12-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0034_auto_20181203_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject2',
            field=models.CharField(blank=True, choices=[('', '--------'), ('Math', 'Math'), ('English', 'English'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer', 'Computer')], default='', max_length=50, null=True),
        ),
    ]
