# Generated by Django 2.1.3 on 2018-12-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0036_auto_20181215_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='t1230',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
