# Generated by Django 2.1.3 on 2018-12-16 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0037_timetable_t1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Tutor'),
        ),
    ]
