# Generated by Django 2.1.3 on 2018-12-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0038_timetable_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fname',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
