# Generated by Django 2.1.3 on 2018-12-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0039_timetable_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timetable',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='CS416Project.Timetable'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('', '--------'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Satrurday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('', '--------'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Satrurday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=50),
        ),
    ]
