# Generated by Django 2.1.3 on 2018-12-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0040_auto_20181222_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'tutor__firstname']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='schedule',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CS416Project.Schedule'),
        ),
    ]
