# Generated by Django 2.1.3 on 2018-12-22 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0041_auto_20181222_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day', 'tutor__firstname']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='timetableId',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CS416Project.Timetable'),
        ),
    ]
