# Generated by Django 2.1.3 on 2018-12-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0042_auto_20181222_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timetableId',
        ),
    ]
