# Generated by Django 2.1.3 on 2018-12-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0043_remove_schedule_timetableid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timetableId',
            field=models.OneToOneField(default='Ken Monday', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Timetable'),
        ),
    ]
