# Generated by Django 2.1.3 on 2018-12-22 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0044_schedule_timetableid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='timetableId',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Timetable'),
        ),
    ]
