# Generated by Django 2.1.3 on 2018-12-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0047_auto_20181222_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('', '--------'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Satrurday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=50)),
                ('From1', models.CharField(choices=[('', '--------'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '1:00'), ('13:30', '1:30'), ('14:00', '2:00'), ('14:30', '2:30'), ('15:00', '3:00'), ('15:30', '3:30'), ('16:00', '4:00'), ('16:30', '4:30'), ('17:00', '5:00'), ('17:30', '5:30'), ('18:00', '6:00'), ('18:30', '6:30'), ('19:00', '7:00'), ('19:30', '7:30'), ('20:00', '8:00'), ('20:30', '8:30')], default='', max_length=50)),
                ('To1', models.CharField(choices=[('', '--------'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '1:00'), ('13:30', '1:30'), ('14:00', '2:00'), ('14:30', '2:30'), ('15:00', '3:00'), ('15:30', '3:30'), ('16:00', '4:00'), ('16:30', '4:30'), ('17:00', '5:00'), ('17:30', '5:30'), ('18:00', '6:00'), ('18:30', '6:30'), ('19:00', '7:00'), ('19:30', '7:30'), ('20:00', '8:00'), ('20:30', '8:30')], default='', max_length=50)),
                ('From2', models.CharField(blank=True, choices=[('', '--------'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '1:00'), ('13:30', '1:30'), ('14:00', '2:00'), ('14:30', '2:30'), ('15:00', '3:00'), ('15:30', '3:30'), ('16:00', '4:00'), ('16:30', '4:30'), ('17:00', '5:00'), ('17:30', '5:30'), ('18:00', '6:00'), ('18:30', '6:30'), ('19:00', '7:00'), ('19:30', '7:30'), ('20:00', '8:00'), ('20:30', '8:30')], default='', max_length=50)),
                ('To2', models.CharField(blank=True, choices=[('', '--------'), ('09:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '1:00'), ('13:30', '1:30'), ('14:00', '2:00'), ('14:30', '2:30'), ('15:00', '3:00'), ('15:30', '3:30'), ('16:00', '4:00'), ('16:30', '4:30'), ('17:00', '5:00'), ('17:30', '5:30'), ('18:00', '6:00'), ('18:30', '6:30'), ('19:00', '7:00'), ('19:30', '7:30'), ('20:00', '8:00'), ('20:30', '8:30')], default='', max_length=50)),
                ('usedhours', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('timetableId', models.OneToOneField(blank=True, default='Ken Monday', null=True, on_delete=django.db.models.deletion.CASCADE, to='CS416Project.Timetable')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CS416Project.Tutor')),
            ],
            options={
                'ordering': ['day', 'tutor__firstname'],
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timetableId',
        ),
    ]
