# Generated by Django 2.1.3 on 2018-12-23 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0048_auto_20181223_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule2',
            name='timetableId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CS416Project.Timetable'),
        ),
    ]
