# Generated by Django 2.1.3 on 2018-12-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0049_auto_20181223_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule2',
            name='timetableId',
        ),
        migrations.RemoveField(
            model_name='schedule2',
            name='tutor',
        ),
        migrations.AddField(
            model_name='schedule',
            name='timetableId',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='CS416Project.Timetable'),
        ),
        migrations.DeleteModel(
            name='Schedule2',
        ),
    ]
