# Generated by Django 2.1.3 on 2018-12-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0052_auto_20181223_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('', '--------'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Satrurday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=50),
        ),
    ]
