# Generated by Django 2.1.3 on 2018-12-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS416Project', '0055_auto_20181223_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timetableId',
        ),
    ]
